### ISSUE TITLE
comparison with http-shutdown

### ISSUE THREAD

**Issue by avindra** [hunterloftis/stoppable#13]
`http-shutdown` seems to do exactly what this package does

https://github.com/thedillonb/http-shutdown

Can you offer a comparison of the features?

**Comment by danielreus** [comment]
I have evaluated both implementations (and several others, but none of the others came anywhere close to being satisfactory), because of your comment. I think the significant differences are:
- stoppable is implemented more efficiently, but: you can EITHER not supply a grace period, in which case keep-alive connections will block the shutdown until either they expire or perform a new request. In other words, idle keep-alive connections will not be closed. OR you can supply a grace period, in which case all connections will be closed after the grace period expires, including those still working on active requests. So it has no way of just terminating idle keep-alive connections AND closing the active keep-alive connections as soon as they become idle
- http-shutdown will terminate idle keep-alive connections immediately and will terminate active keep-alive connections as soon as they become idle. But the implementation is less efficient.

It would be awesome if the best of both of these would be combined. Which I think should be perfectly doable.

**Comment by llwt** [comment]
@danielreus Are you sure it doesn't handle active connections? 

My interpretation here is that it will close all idle on shutdown request, and anything active will be closed out with the `req.socket.end()` call since `stopped` is set in the `stop` call.

```javascript
function onRequest (req, res) {
    reqsPerSocket.set(req.socket, reqsPerSocket.get(req.socket) + 1)
    res.once('finish', () => {
      const pending = reqsPerSocket.get(req.socket) - 1
      reqsPerSocket.set(req.socket, pending)
      if (stopped && pending === 0) {
        req.socket.end()
      }
    })
  }
```

**Comment by avindra** [comment]
Thanks for the info. Closing the issue which can remain as documentation.
